### ISSUE TITLE
Idea: personalized lists of publications

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/biaslab-hugo#150]
I had an idea to improve the website for outsiders a bit. Currently the team members pages feel a bit repetitive to me. Would it be possible to extend this page with an automatically filtered publication list, such that each member has a personalized list of publications on their profile page. This should make it also a bit clearer to outsiders what everyone is actually working on, without having to go through the general publication list. I am not saying that we _have to_ implement this, but would rather have a discussion and share thoughts.

**Comment by abpolym** [comment]
That's a nice idea. We might have a filter/search functionality in the future provided by an alternative to hugo (wowchemy) - when we switch to that we probably can take care of this issue at the same time, too!

**Comment by Nimrais** [comment]
Implemented in [PR 62](https://github.com/biaslab/hugo-academic-group/pull/62).
