### ISSUE TITLE
Add paper Adaptive Optimizer Design for Constrained VI

### ISSUE THREAD

**Issue by Nimrais** [biaslab/biaslab-hugo#156]
SITB 2022 website: https://sites.google.com/view/sitb2022/home, proceedings: https://www.dropbox.com/s/i0q8x74xhkixvue/Proceedings-SITB2022.pdf?dl=0

**Comment by abpolym** [comment]
Resolved: Added [paper](https://biaslab.github.io/publication/adaptive_optimizer_design_for_constrained_variational_inference/). Had to cut the pdf from as follows:

`qpdf Proceedings-SITB2022.pdf alp_adaptive_optimizer_cvi.pdf --pages Proceedings-SITB2022.pdf 95-100 --`
