### ISSUE TITLE
Add RxInfer.jl to the Projects tab

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/biaslab-hugo#164]
In the same way as `ForneyLab`, `Rocket` and `ReactiveMP`

**Comment by abpolym** [comment]
@bvdmitri I think you meant the `software` tab :)?

Done!

**Comment by albertpod** [comment]
Hi @abpolym, thanks for adding RxInfer to the software tab.

We still need to add `RxInfer` to the [Projects](https://biaslab.github.io/project/). 
It might be okay to redirect to [RxInfer](www.rxinfer.ml) the main page.
What do you think @bertdv?

**Comment by bertdv** [comment]
Yes, but I think our biaslab.org needs a re-design makeover. For now, It's OK to list rxinfer in the software tab. In the re-designed biaslab.org, rxinfer should take a much more prominent role as the major output of our lab, supported by (application) projects and method papers. So, rxinfer is not just another project, but a major product.

**Comment by bvdmitri** [comment]
The title of the issue is misleading IMO. This one is fixed, if we need a re-design I would suggest opening a new issue.

**Comment by bertdv** [comment]
agreed, since RxInfer has been added to the Project tab, i will close this issue.
