### ISSUE TITLE
Cannot clone repository

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/biaslab-hugo#186]
Hi guys, I am unable to clone the repository and get the following error message
```
Cloning into 'C:\Users\...\Desktop\biaslab\biaslab-hugo'...
remote: Enumerating objects: 5149, done.        
remote: Counting objects: 100% (1427/1427), done.        
remote: Compressing objects: 100% (586/586), done.        
remote: Total 5149 (delta 899), reused 1305 (delta 825), pack-reused 3722        
Receiving objects: 100% (5149/5149), 196.08 MiB | 13.06 MiB/s, done.
Resolving deltas: 100% (3234/3234), done.
error: invalid path 'content/publication/realising_synthetic_active_inference_agents,_part_i:_epistemic_objectives_and_graphical_specification_language.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
There also seems to be an issue with the part 2 paper. If I were to guess, then it might be related to the colon in the file name that breaks windows.

**Comment by Nimrais** [comment]
Hi Bart, yes, you are right this two filenames are not compatible with Windows path system. I have fixed them, to avoid it in the future I added a CI check that scan over filenames and test them over simple rule: a path can not contain any of windows forbidden path symbols : < > ;  ? \.

**Comment by bartvanerp** [comment]
Thanks @Nimrais! seems to be resolved now.
