### ISSUE TITLE
add picture to project descriptions at homepage

### ISSUE THREAD

**Issue by bertdv** [biaslab/biaslab-hugo#42]
I think it is important to make the frontpage of biaslab.org attractive, ie, less text more images. I suggest that we upgrade the `projects` strip with an image for each project and less text. A bit more like this; https://www.cs.toronto.edu/~duvenaud/ , see `Selected papers` section. Later, if this works, we could extend this to the `publications` and `blog` sections. The idea is that each project, publication or blog gets an image, a bit of text and one or more buttons for more information.

**Comment by ivan-bocharov** [comment]
You can see the preliminary design in the `index-redesign` branches of [biaslab-hugo](https://github.com/biaslab/biaslab-hugo/) and [hugo-academic-group](https://github.com/biaslab/hugo-academic-group).

![screen shot 2017-08-08 at 17 06 32](https://user-images.githubusercontent.com/706421/29079031-55fcf988-7c5c-11e7-873d-f7e26a104031.png)

**Comment by bertdv** [comment]
I think this is great. you can go ahead with this and (for now) use the default pics.
