### ISSUE TITLE
Add EUSIPCO paper to BIASlab website publications folder

### ISSUE THREAD

**Issue by bertdv** [biaslab/biaslab-hugo#51]

**Comment by ThijsvdLaar** [comment]
Added paper to publications.

**Comment by bertdv** [comment]
THanks for setting this on the website. Just one thing: the project buton on https://biaslab.github.io/publication/variational_slf_in_ssm/ opens the PHLC project page. Please delete teh button.

**Comment by ThijsvdLaar** [comment]
Removed the button from the page (hard refresh to view the changes). @bertdv I'll leave it to you to close the issue.

**Comment by marcocox** [comment]
The paper in the EUSIPCO proceedings is slightly different from the version on our website (it contains an additional copyright notice etc.). Don't know if this is a problem, but I just wanted to mention it.

**Comment by ThijsvdLaar** [comment]
That is correct, this notice is required when publishing it on your own website.

**Comment by bertdv** [comment]
Thanks for deleting the button. The CR notice is fine, thanks.

**Comment by marcocox** [comment]
Ok, but I meant that the version in the official proceedings has a copyright notice that's not in the version on our website.

**Comment by ThijsvdLaar** [comment]
Oh yeah, you're right, they must have added that when creating the proceedings because I never saw it before. Anyway, I followed their instructions so I'll leave it like this.
