### ISSUE TITLE
Propose a sub-menu scheme 

### ISSUE THREAD

**Issue by bertdv** [biaslab/biaslab-hugo#52]
Investigate the options for a sub-menu. 

For instance, we want a menu item: `Vacancies`, with sub-items `PhD`, `MSc projects`, `BSc projects`.

**Comment by ivan-bocharov** [comment]
The demo of sub-menu functionality is available in `dropdown-menu` branches of `biaslab-hugo` and `hugo-academic-group` repositories.

**Comment by bertdv** [comment]
This looks fine. Thank you. Can be merged
