### ISSUE TITLE
Propose method to show mission statement on landing strip

### ISSUE THREAD

**Issue by bertdv** [biaslab/biaslab-hugo#56]
Propose a method to display the following on our landing page (see also deepmind landing page):

Developing autonomous agents that learn purposeful behavior from situated environmental interactions . Using these agents to automate the development of new signal processing algorithms.

**Comment by ivan-bocharov** [comment]
First version of new landing with mission statement can be tested in `new-landing` [branch](https://github.com/biaslab/biaslab-hugo/tree/new-landing).

**Comment by bertdv** [comment]
Awesome, I shortened the text a bit. Please merge. Great job.
