### ISSUE TITLE
Move 5SSB0 to BIASlab site

### ISSUE THREAD

**Issue by bertdv** [biaslab/biaslab-hugo#83]
Move http://bertdv.github.io/teaching/AIP-5SSB0/ to BIASLab site. Preferably before end of year.

**Comment by bertdv** [comment]
great, thx

**Comment by ivan-bocharov** [comment]
The course hasn't been fully moved to BIASlab website yet. For example, images are still being served from your GitHub repository. I suggest we keep this issue open until we finish with that.

**Comment by ivan-bocharov** [comment]
Related to #81
